# Generated by Django 5.0.3 on 2024-03-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sesler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ses', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sozcukler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sozcuk', models.CharField(max_length=50)),
                ('anlam', models.TextField()),
                ('koken', models.CharField(max_length=50)),
            ],
        ),
    ]
