# Generated by Django 5.0.3 on 2024-03-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozluk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozcukler',
            name='karsilik',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sozcukler',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sesler',
            name='ses',
            field=models.CharField(max_length=50),
        ),
    ]
