# Generated by Django 5.0.3 on 2024-03-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozluk', '0002_sozcukler_karsilik_sozcukler_slug_alter_sesler_ses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sozcukler',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
