# Generated by Django 5.0.3 on 2024-03-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozluk', '0003_alter_sozcukler_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sozcukler',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
