# Generated by Django 5.0.3 on 2024-03-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozluk', '0004_alter_sozcukler_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sozcukler',
            name='karsilik',
            field=models.CharField(max_length=200),
        ),
    ]
