# Generated by Django 5.0.3 on 2024-03-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozluk', '0005_alter_sozcukler_karsilik'),
    ]

    operations = [
        migrations.AddField(
            model_name='diller',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sesler',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
