# Generated by Django 5.0.3 on 2024-03-06 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozluk', '0006_diller_slug_sesler_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozcukler',
            name='dil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sozcukler_dil', to='sozluk.diller'),
        ),
        migrations.AddField(
            model_name='sozcukler',
            name='ses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sozcukler_ses', to='sozluk.sesler'),
        ),
    ]
