# Generated by Django 5.0.3 on 2024-03-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sozluk', '0007_sozcukler_dil_sozcukler_ses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sozcukler',
            options={'ordering': ['sozcuk']},
        ),
    ]
