# Generated by Django 5.0.3 on 2024-03-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sozluk', '0008_alter_sozcukler_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sozcukler',
            options={'ordering': ['-sozcuk']},
        ),
    ]
